---
# tasks file for install-k8s-master-node

- name: Copy kube-config for init
  become: yes
  copy:
    src: kube-config.yaml
    dest: /opt/kubec-config.yaml

- name: Init the cluster
  become: yes
  shell: |
    kubeadm init --apiserver-advertise-address {{ MASTER_IP }} \
                 --pod-network-cidr {{ POD_NETWORK_CIDR }} \
                 --config /opt/kubec-config.yaml

- name: Clean kube-config after init
  become: yes
  file:
    state: absent
    dest: /opt/kubec-config.yaml
