---
# tasks file for install-k8s-master-node

- name: Copy kube-config for init
  become: yes
  template:
    src: kube-config.yaml
    dest: /opt/kubec-config.yaml

- name: Clean install
  become: yes
  shell: |
    kubeadm reset -f

- name: Init the cluster
  become: yes
  shell: |
    kubeadm init --config /opt/kubec-config.yaml

- name: Clean kube-config after init
  become: yes
  file:
    state: absent
    dest: /opt/kubec-config.yaml
